### ISSUE TITLE
Cannot find the specified file

### ISSUE THREAD

**Issue by lordvader171** [darthRebel/swcnoops#86]
When I try to connect the server with the client I get this error:
2022-09-11 17:10:49,451 ERROR SparkMain - Caught exception 
java.io.FileNotFoundException: c:\swcnoops\swcFiles\1541022029\connection_test.txt (Cannot find the specified file)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at swcnoops.server.SparkMain$GetFile.handle(SparkMain.java:94)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by darthRebel** [comment]
You need to get the assetbundles from the game client. These are stored in the game cache of your client. The connection file is just an empty file you can make that.

**Comment by lordvader171** [comment]
I had found this link http://redirect.viglink.com/?key=71fe2139a887ad501313cd8cce3053c5&subId=7069473&u=https%3A//www.mediafire.com/file/albhe59f5aen4uy/Star+Wars+Commander+cache.zip/file
and there were .assetbundle files

**Comment by lordvader171** [comment]
I understood I had found this link http://redirect.viglink.com/?key=71fe2139a887ad501313cd8cce3053c5&subId=7069473&u=https%3A//www.mediafire.com/file/albhe59f5aen4uy/Star+Wars+Commander+cache.zip/file and thought it had all the assetbundle files

**Comment by lordvader171** [comment]
I understood I had found this link http://redirect.viglink.com/?key=71fe2139a887ad501313cd8cce3053c5&subId=7069473&u=https%3A//www.mediafire.com/file/albhe59f5aen4uy/Star+Wars+Commander+cache.zip/file and thought it had all the assetbundle files.

**Comment by lordvader171** [comment]
I understood I had found this link http://redirect.viglink.com/?key=71fe2139a887ad501313cd8cce3053c5&subId=7069473&u=https%3A//www.mediafire.com/file/albhe59f5aen4uy/Star+Wars+Commander+cache.zip/file and thought it had all the assetbundle files.

**Comment by darthRebel** [comment]
I am hunting for as many asset bundles as I can find, basically anyone who has installed the game and can access the cached files, I want. To turn a cache file back to an assetBundle it just needs to be renamed (only difference is that it is no compressed compared to the original).
